# .github/workflows/deploy.yml
:contentReference[oaicite:3]{index=3}

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  :contentReference[oaicite:4]{index=4}

concurrency:
  group: "pages"
  :contentReference[oaicite:5]{index=5}

jobs:
  build:
    :contentReference[oaicite:6]{index=6}
    environment:
      :contentReference[oaicite:7]{index=7}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    :contentReference[oaicite:8]{index=8}
    permissions:
      pages: write
      :contentReference[oaicite:9]{index=9}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3